import { test } from 'uvu'
import { equal } from 'uvu/assert'
import { be_, Ctx, ctx_, ctx__delete } from '../index.js'
test('be_|Map', ()=>{
	const ctx = ctx_()
	const root_ = be_('root_', ()=>1)
	const child_ = be_('child_', ctx=>root_(ctx) + 1)
	const child1_ = be_('child1_', ctx=>root_(ctx) + child_(ctx))
	equal(root_(ctx), 1)
	equal(child_(ctx), 2)
	equal(child1_(ctx), 3)
})
test('be_|simple array', ()=>{
	const ctx0 = ctx_()
	const ctx1 = ctx_()
	const ctx = [ctx0, ctx1]
	const root_ = be_('root_', ()=>1)
	equal(root_(ctx1), 1)
	equal(root_(ctx), 1)
	equal(ctx0.has(root_), false)
	equal(ctx1.has(root_), true)
	const child_ = be_('child_', ctx=>root_(ctx) + 1)
	equal(child_(ctx), 2)
	equal(ctx0.has(child_), true)
	equal(ctx1.has(child_), false)
})
test('be_|nested array', ()=>{
	const ctx0 = ctx_()
	const ctx1 = ctx_()
	const ctx2 = ctx_()
	const ctx3 = ctx_()
	const ctx = [[[ctx0], ctx1], [ctx2, ctx3]]
	const root_ = be_('root_', ()=>1)
	equal(root_(ctx3), 1)
	equal(root_(ctx), 1)
	equal(ctx0.has(root_), false)
	equal(ctx1.has(root_), false)
	equal(ctx2.has(root_), false)
	equal(ctx3.has(root_), true)
	const child_ = be_('child_', ctx=>root_(ctx) + 1)
	equal(child_(ctx), 2)
	equal(ctx0.has(child_), true)
	equal(ctx1.has(child_), false)
	equal(ctx2.has(child_), false)
	equal(ctx3.has(child_), false)
})
test('be_|is_source_', ()=>{
	const ctx0 = ctx_()
	const ctx1 = ctx_()
	ctx1.set('matching', true)
	const ctx = [ctx0, ctx1]
	const root_ = be_('root_', ()=>1, {
		is_source_(map_ctx) {
			return !!map_ctx.get('matching')
		}
	})
	equal(root_(ctx), 1)
	equal(ctx0.has(root_), false)
	equal(ctx1.has(root_), true)
})
test('Ctx|NestedMapCtx', ()=>{
	const ctx0 = ctx_()
	const ctx1 = ctx_()
	ctx1.set('matching', true)
	const ctx = [ctx0, ctx1]
	const nested__ctx_ = be_<Ctx>('nested__ctx_', ctx=>[ctx])
	equal(nested__ctx_(ctx), [[ctx0, ctx1]])
})
test('ctx__delete', ()=>{
	const ctx0 = ctx_()
	const val_ = be_<boolean>('val_', ()=>true)
	equal(val_(ctx0), true)
	equal(ctx0.get(val_), true)
	equal(ctx0.get('val_'), new Map([[val_, true]]))
	ctx__delete(ctx0, val_)
	equal(ctx0.has(val_), false)
	equal(ctx0.has('val_'), false)
	const ctx1 = ctx_()
	const nested__ctx = [ctx0, ctx1]
	equal(val_(ctx0), true)
	equal(val_(ctx1), true)
	equal(val_(nested__ctx), true)
	equal(ctx0.get('val_'), new Map([[val_, true]]))
	equal(ctx1.get('val_'), new Map([[val_, true]]))
	ctx__delete(nested__ctx, val_)
	equal(ctx0.has(val_), false)
	equal(ctx0.has('val_'), false)
	equal(ctx1.has(val_), false)
	equal(ctx1.has('val_'), false)
})
test.run()
